from app.models.schemas import AnalysisResponse, ExtractedElements, Issue, IssueSeverity


SEVERITY_EMOJI = {
    IssueSeverity.INFO: "ℹ️",
    IssueSeverity.WARNING: "⚠️",
    IssueSeverity.CRITICAL: "🚨",
}


def generate_report_markdown(
    filename: str,
    pages_analyzed: int,
    elements: ExtractedElements,
    issues: list[Issue],
) -> str:
    lines: list[str] = [
        f"# Floor Plan Review: {filename}",
        "",
        f"**Pages analyzed:** {pages_analyzed}",
        "",
        "## Summary",
        "",
        f"- **Rooms:** {len(elements.rooms)}",
        f"- **Doors:** {len(elements.doors)}",
        f"- **Windows:** {len(elements.windows)}",
        f"- **Stairs:** {len(elements.stairs)}",
        f"- **Dimensions noted:** {len(elements.dimensions)}",
        f"- **Issues found:** {len(issues)}",
        "",
    ]

    if elements.rooms:
        lines += ["## Rooms", ""]
        for room in elements.rooms:
            area = (
                f" (~{room.approximate_area_sqft} sq ft)"
                if room.approximate_area_sqft
                else ""
            )
            lines.append(f"- **{room.name}**{area}")
            if room.notes:
                lines.append(f"  - {room.notes}")
        lines.append("")

    if issues:
        lines += ["## Issues & Recommendations", ""]
        for issue in sorted(issues, key=lambda i: i.severity.value, reverse=True):
            emoji = SEVERITY_EMOJI.get(issue.severity, "")
            lines += [
                f"### {emoji} {issue.title} ({issue.severity.value})",
                "",
                f"**Category:** {issue.category}",
                "",
                issue.description,
                "",
            ]
            if issue.recommendation:
                lines += [f"**Recommendation:** {issue.recommendation}", ""]
            if issue.code_reference:
                lines += [f"**Reference:** {issue.code_reference}", ""]
    else:
        lines += [
            "## Issues & Recommendations",
            "",
            "No significant issues were identified. Verify with a licensed professional.",
            "",
        ]

    lines += [
        "---",
        "",
        "*This report is generated by FirstPass for informational purposes only "
        "and is not a substitute for professional architectural or code review.*",
    ]

    return "\n".join(lines)
