#!/usr/bin/env python3
"""One-time bulk import of CodeComply's (~/CADAI) pre-chunked, real 2025
California code text into FirstPass's corpus. Fills the gap the live
refresh_corpus.py pipeline doesn't cover: full CBC/CRC/CEC/CMC/CPC/CGBC/CFC
text (not 3-sentence stubs) plus complete LAMC and Santa Ana municipal code.

CADAI's chunks (lib/raw/chunks/*.md, generated by its chunk_codes.py) are
already section-bounded with real metadata:
    ---
    CHUNK_ID: CRC-R101
    CODE_BODY: California Residential Code
    SECTION: R101
    TITLE: SCOPE AND GENERAL REQUIREMENTS
    APPLIES_TO: ADU, residential
    SKIP: false
    AMENDMENT_OF: null
    CROSS_REFERENCES: R101.1, R101.2, R309, ...
    CONTENT:
    <verbatim OCR'd code text>
    ---
This script parses those blocks directly into FirstPass's CodeChunk shape
(src/lib/code-db.ts) rather than routing them through FirstPass's own
chunk_codes.py (whose legal-heading auto-detector is for raw OCR .txt, not
already-chunked markdown, and re-running it would risk mangling this).

The 7 code-body files are STATE law — shared into every city's corpus, same
convention already used for state ADU sources. LAMC is Los Angeles-only.
Santa Ana's file seeds a brand-new santa-ana-ca city.

Also retires the old low-quality stand-ins these replace: LA's giant
building_regulations_lamc.txt bulk dump (dwarfing everything else,
inconsistent citations) and the four ~1KB "representative excerpt" stubs
(building_code_cbc.txt, residential_code_crc.txt, plumbing_code_cpc.txt,
green_code_calgreen.txt) that were never the real code.

Usage:
    uv run python scripts/import_cadai_corpus.py
"""

from __future__ import annotations

import json
import re
import shutil
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CITIES_DIR = ROOT / "data" / "cities"
CODES_DIR = ROOT / "data" / "codes" / "ca-2025"  # shared-state provenance copies
CADAI_CHUNKS = Path("/Users/kiromoussa/CADAI/lib/raw/chunks")

CHUNK_RE = re.compile(
    r"^CHUNK_ID:\s*(?P<id>.+?)\s*\n"
    r"CODE_BODY:\s*(?P<code_body>.+?)\s*\n"
    r"SECTION:\s*(?P<section>.+?)\s*\n"
    r"TITLE:\s*(?P<title>.+?)\s*\n"
    r"APPLIES_TO:\s*(?P<applies_to>.*?)\s*\n"
    r"SKIP:\s*(?P<skip>true|false)\s*\n"
    r"AMENDMENT_OF:\s*(?P<amendment_of>.*?)\s*\n"
    r"CROSS_REFERENCES:\s*(?P<cross_refs>.*?)\s*\n"
    r"CONTENT:\s*\n(?P<content>.*?)(?=\n---\s*\n|\Z)",
    re.DOTALL | re.MULTILINE,
)

# Mirrors src/lib/code-db.ts RULE_TERMS + corpus-compliance.ts topic keywords —
# best-effort tagging so imported chunks rank well, not required for basic
# lexical reachability (the real text alone is already searchable).
TOPIC_TERMS: dict[str, list[str]] = {
    "maxSize": ["floor area", "square feet", "square foot"],
    "height": ["height", "feet in height", "roof pitch", "stories", "story"],
    "setbackSide": ["side setback", "side yard"],
    "setbackRear": ["rear setback", "rear yard"],
    "setbackFront": ["front setback", "front yard"],
    "lotCoverage": ["lot coverage", "buildable area"],
    "far": ["floor area ratio"],
    "parking": ["parking", "off-street", "spaces per unit"],
    "egress": ["egress", "emergency escape", "exit discharge", "means of egress"],
    "fireProtection": ["sprinkler", "fire-resistance", "fire resistance", "fire separation"],
    "ventilation": ["ventilation", "combustion air", "makeup air"],
    "waterEfficiency": ["water closet", "gallons per", "gpf", "gpm", "flow rate"],
    "smokeAlarm": ["smoke alarm", "carbon monoxide"],
    "evCharging": ["ev charging", "electric vehicle"],
    "solar": ["solar", "photovoltaic"],
    "occupancy": ["occupancy classification", "group r"],
    "foundation": ["foundation", "footing", "soils"],
}

# (source filename, code_body prefix -> registry key, category, kind)
STATE_CODE_FILES = [
    ("gov.ca.bsc.residential.2025_djvu_chunked.md", "residential", "gov.ca.bsc.residential.2025"),
    ("gov.ca.bsc.building.2.2025_djvu_chunked.md", "building", "2022californiabu01unse"),
    ("gov.ca.bsc.electrical.2025_djvu_chunked.md", "electrical", None),
    ("gov.ca.bsc.mechanical.2025_djvu_chunked.md", "mechanical", None),
    ("gov.ca.bsc.plumbing.2025_djvu_chunked.md", "plumbing", None),
    ("gov.ca.bsc.green.2025_djvu_chunked.md", "green", "2022californiagr00unse"),
    ("gov.ca.bsc.fire.2025_djvu_chunked.md", "fire", None),
]

# Raw files + chunks.json sourceIds these imports fully supersede.
LA_RETIRE_RAW = [
    "building_regulations_lamc.txt",
    "building_code_cbc.txt",
    "residential_code_crc.txt",
    "plumbing_code_cpc.txt",
    "green_code_calgreen.txt",
]


def clean_content(text: str) -> str:
    text = re.sub(r"\n{3,}", "\n\n", text.strip())
    text = re.sub(r"[ \t]{2,}", " ", text)
    return text


def parse_chunk_file(path: Path) -> list[dict]:
    raw = path.read_text(encoding="utf-8", errors="replace")
    out = []
    for m in CHUNK_RE.finditer(raw):
        if m.group("skip") == "true":
            continue
        content = clean_content(m.group("content"))
        if len(content) < 30:
            continue
        out.append(
            {
                "chunk_id": m.group("id").strip(),
                "code_body": m.group("code_body").strip(),
                "section": m.group("section").strip(),
                "title": m.group("title").strip(),
                "applies_to": m.group("applies_to").strip(),
                "cross_refs": m.group("cross_refs").strip(),
                "content": content,
            }
        )
    return out


def infer_topics(title: str, content: str, applies_to: str) -> list[str]:
    # code-db.ts's scoreChunk() gives ANY topic-tagged chunk a flat +5 bonus —
    # a big deal against a corpus this size, where lexical hit counts are
    # usually 1-3. Matching against the first 1500 chars of BODY text tagged
    # sections that only mention a topic in passing (e.g. an elevator standby-
    # power section that happens to discuss machine-room ventilation got
    # tagged "ventilation" and then outscored the actual ventilation
    # sections). The title is what a section is actually ABOUT — match there
    # only, so the tag stays a precise signal instead of a loose one.
    topics = [key for key, terms in TOPIC_TERMS.items() if any(t in title.lower() for t in terms)]
    topics += [t.strip().lower() for t in applies_to.split(",") if t.strip()]
    return sorted(set(topics))


def to_code_chunks(
    parsed: list[dict], source_id: str, category: str, jurisdiction_label: str
) -> list[dict]:
    # CADAI's upstream chunker occasionally mis-detects the same section
    # number twice in OCR'd text (a table-of-contents mention, a
    # cross-reference table, and the real section body all matching its
    # numeric-line heading pattern) — keep every chunk (nothing is dropped)
    # but disambiguate the id so none of them silently collide.
    seen_ids: dict[str, int] = {}
    chunks = []
    for c in parsed:
        cite = f"{c['code_body']} §{c['section']}"
        section_label = f"{cite} — {c['title']}" if c["title"] else cite
        context = f"{jurisdiction_label} · {c['code_body']} · §{c['section']}"
        if c["cross_refs"] and c["cross_refs"] != "null":
            context += f" (cross-refs: {c['cross_refs']})"

        base_id = re.sub(r"[^a-z0-9]+", "-", c["chunk_id"].lower()).strip("-")
        seen_ids[base_id] = seen_ids.get(base_id, 0) + 1
        chunk_id = base_id if seen_ids[base_id] == 1 else f"{base_id}-dup{seen_ids[base_id]}"

        chunks.append(
            {
                "id": chunk_id,
                "section": section_label,
                "topics": infer_topics(c["title"], c["content"], c["applies_to"]),
                "text": c["content"],
                "sourceId": source_id,
                "category": category,
                "context": context,
                "citation": cite,
                "tokensEst": max(1, len(c["content"]) // 4),
            }
        )
    return chunks


def load_json(path: Path, default):
    return json.loads(path.read_text(encoding="utf-8")) if path.exists() else default


def save_json(path: Path, data) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(data, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")


def ensure_source(meta: dict, filename: str, title: str, url: str) -> str:
    raw_sources: dict = meta.setdefault("rawSources", {})
    if filename in raw_sources:
        return raw_sources[filename]
    existing = {s["id"] for s in meta.get("sources", [])}
    n = 1
    while f"S{n}" in existing:
        n += 1
    sid = f"S{n}"
    raw_sources[filename] = sid
    meta.setdefault("sources", []).append({"id": sid, "url": url, "title": title})
    return sid


def retire_sources(meta: dict, chunks: list[dict], filenames: list[str]) -> list[dict]:
    """Drop chunks belonging to superseded sourceIds and remove their raw-file
    registration, but keep the sourceId entries in `sources[]` (older Findings
    may still reference them by id in a persisted report — harmless to leave)."""
    retire_ids = set()
    for fn in filenames:
        sid = meta.get("rawSources", {}).pop(fn, None)
        if sid:
            retire_ids.add(sid)
    return [c for c in chunks if c.get("sourceId") not in retire_ids]


def import_state_codes_into(slug: str) -> int:
    meta = load_json(CITIES_DIR / slug / "meta.json", {"slug": slug, "sources": [], "rawSources": {}})
    chunks = load_json(CITIES_DIR / slug / "chunks.json", [])

    added = 0
    for filename, category, archive_item in STATE_CODE_FILES:
        path = CADAI_CHUNKS / filename
        if not path.exists():
            print(f"  ! missing {filename}, skipping")
            continue
        parsed = parse_chunk_file(path)
        url = f"https://archive.org/details/{archive_item}" if archive_item else "https://www.dgs.ca.gov/BSC/Codes"
        title = parsed[0]["code_body"] + " (2025)" if parsed else category
        sid = ensure_source(meta, f"cadai-{filename}", f"{title} — Title 24", url)
        new_chunks = to_code_chunks(parsed, sid, category, "California")
        # Replace any prior import from this exact source (idempotent re-run).
        chunks = [c for c in chunks if c.get("sourceId") != sid] + new_chunks
        added += len(new_chunks)
        print(f"  {filename}: {len(new_chunks)} chunks -> sourceId {sid} (category={category})")

    save_json(CITIES_DIR / slug / "chunks.json", chunks)
    save_json(CITIES_DIR / slug / "meta.json", meta)
    return added


def import_los_angeles() -> int:
    slug = "los-angeles-ca"
    meta = load_json(CITIES_DIR / slug / "meta.json", {})
    chunks = load_json(CITIES_DIR / slug / "chunks.json", [])

    print("  retiring superseded stub/bulk sources...")
    chunks = retire_sources(meta, chunks, LA_RETIRE_RAW)
    for fn in LA_RETIRE_RAW:
        p = CITIES_DIR / slug / "raw" / fn
        if p.exists():
            p.unlink()
            print(f"    removed raw/{fn}")

    path = CADAI_CHUNKS / "Los Angeles, CA Municipal Code_chunked.md"
    parsed = parse_chunk_file(path)
    sid = ensure_source(
        meta,
        "cadai-lamc.md",
        "Los Angeles Municipal Code (full, chunked)",
        "https://codelibrary.amlegal.com/codes/los_angeles/latest/lamc/0-0-0-1",
    )
    new_chunks = to_code_chunks(parsed, sid, "city", "Los Angeles, CA")
    chunks = [c for c in chunks if c.get("sourceId") != sid] + new_chunks
    print(f"  LAMC full: {len(new_chunks)} chunks -> sourceId {sid}")

    save_json(CITIES_DIR / slug / "chunks.json", chunks)
    save_json(CITIES_DIR / slug / "meta.json", meta)
    return len(new_chunks)


def import_santa_ana() -> int:
    slug = "santa-ana-ca"
    meta_path = CITIES_DIR / slug / "meta.json"
    is_new = not meta_path.exists()
    meta = load_json(
        meta_path,
        {
            "slug": slug,
            "city": "Santa Ana",
            "state": "CA",
            "jurisdictionId": slug,
            "projectTypes": ["detached_adu", "attached_adu", "single_family", "multi_family"],
            "sources": [],
            "rawSources": {},
        },
    )
    chunks = load_json(CITIES_DIR / slug / "chunks.json", [])

    path = CADAI_CHUNKS / "Santa Ana, CA Code of Ordinances_chunked.md"
    parsed = parse_chunk_file(path)
    sid = ensure_source(
        meta,
        "cadai-sac.md",
        "Santa Ana Code of Ordinances (full, chunked)",
        "https://library.municode.com/ca/santa_ana/codes/code_of_ordinances",
    )
    new_chunks = to_code_chunks(parsed, sid, "city", "Santa Ana, CA")
    chunks = [c for c in chunks if c.get("sourceId") != sid] + new_chunks
    print(f"  {'[new city] ' if is_new else ''}Santa Ana municipal: {len(new_chunks)} chunks -> sourceId {sid}")

    save_json(CITIES_DIR / slug / "chunks.json", chunks)
    save_json(CITIES_DIR / slug / "meta.json", meta)
    return len(new_chunks)


def copy_provenance_docs() -> None:
    """Keep an original-source copy for audit — not read by the app at
    runtime, and NOT under data/cities/*/raw/ so a future chunk_codes.py run
    never tries to re-chunk already-chunked markdown."""
    CODES_DIR.mkdir(parents=True, exist_ok=True)
    for filename, *_ in STATE_CODE_FILES:
        src = CADAI_CHUNKS / filename
        if src.exists():
            shutil.copy2(src, CODES_DIR / filename)
    for name in ("Los Angeles, CA Municipal Code_chunked.md", "Santa Ana, CA Code of Ordinances_chunked.md"):
        src = CADAI_CHUNKS / name
        if src.exists():
            shutil.copy2(src, CODES_DIR / name)


def main() -> None:
    if not CADAI_CHUNKS.exists():
        raise SystemExit(f"CADAI chunks not found at {CADAI_CHUNKS}")

    print("=== alameda-ca: shared state codes ===")
    import_state_codes_into("alameda-ca")

    print("=== los-angeles-ca: shared state codes + full LAMC ===")
    import_state_codes_into("los-angeles-ca")
    import_los_angeles()

    print("=== santa-ana-ca: shared state codes + full municipal code ===")
    import_santa_ana()  # creates meta.json with city/state/projectTypes first
    import_state_codes_into("santa-ana-ca")

    print("=== copying provenance source docs to data/codes/ca-2025/ ===")
    copy_provenance_docs()

    print("Done.")


if __name__ == "__main__":
    main()
